spring.rsocket.server.mapping-path: /rsocket
spring.rsocket.server.transport: websocket
server.port: 8080

logging:
  level:
    org.springframework: ERROR
    pp.ua.ssenko: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"
